### ISSUE TITLE
Infinite blocking GetRawFile(...).Result on SECOND calls

### ISSUE THREAD

**Issue by jeremy-waguet** [skazantsev/WebDavClient#53] opened 2020-04-16 18:42 UTC
Since I upgraded to version 2.5.0, in my program I am using synchronous IO (since I am working in a Windows Form background worker)

Sample code:
```c#
var retRemoteGetTask1 = client.GetRawFile(filename1);
retRemoteGetTask1.Wait(); // Works !
var retRemoteResult1 = retRemoteGetTask1.Result; // retRemoteResult1 is fully filled

var retRemoteGetTask2 = client.GetRawFile(filename2);
retRemoteGetTask2.Wait(); // Infinite wait unless I break the debugger and "quick watch the retRemoteGetTask2 variable) !
//Quick Watching retRemoteGetTask2 : { Id = 41, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}" }
var retRemoteResult2 = retRemoteGetTask2.Result; // NEVER Reaching this line
```

**Comment by skazantsev** [comment] 2020-04-16 19:10
Hi @jeremy-waguet ,

It looks like a regression bug due to a missing await :(
I can release a fix today in a version 2.6.0.
Thank you for bringing this up.

**Comment by skazantsev** [comment] 2020-04-16 19:32
The version 2.6.0 is released in NuGet.
I also unlisted the version 2.5.0 and marked it as deprecated in NuGet.
Thanks for taking time to report it and sorry for inconvenience.

**Closed by skazantsev** 2020-04-16 19:32 UTC
Labels: bug

**Comment by jeremy-waguet** [comment] 2020-04-16 20:17
Your welcome for this very quick fix !JeremyOn 16 Apr 2020 21:33, Sergey Kazantsev <notifications@github.com> wrote:
The version 2.6.0 is released in NuGet.
I also unlisted the version 2.5.0 and marked it as deprecated in NuGet.
Thanks for taking time to report it and sorry for inconvenience.
